### ISSUE TITLE
RE: Tensorflow, Bazel, and Bazelisk: armhf on BBAI?

### ISSUE THREAD

**Issue by silver2row** [bazelbuild/bazelisk#108]
Hello,

I am trying to use my 32 bit controller, the BBAI, to compile some source and get tensorflow on my machine so that I can use openCV one day. I came across this idea of Bazel and Bazelisk on the tensorflow site under install. 

I am stuck w/ this bunch of error messages:

    The system is out of resources.
    Consult the following stack trace for details.
    java.lang.OutOfMemoryError: Java heap space

Is there a light version or another way to go about getting tensorflow on my Debian Stretch Distro? I saw that Buster will start to incorporate items for development. I am on kernel 4.14.x.

Seth

P.S. I know this is a RAM issue, most likely on my end, but I am reaching out nevertheless with trying to find ways to get tensorflow on the machine of choice. If you know what issues I am describing, please do reply.

**Comment by philwo** [comment]
Hi Seth,

are you building directly on your BBAI? If I read this correctly, it has a dual-core CPU and 1GB of RAM, right? The TensorFlow build is quite heavy, I'm not sure if we can get this to work...

It might be easier to build on a machine or VM with a compatible architecture, but more CPU power and RAM. Ideally, TensorFlow would offer prebuilt binaries for these platforms, as it is very unrealistic to build it directly on them. Even if it would work, the build would probably take an entire day. Have you asked on the TensorFlow issue tracker about this already?

But regarding your build, I assume you already managed to get Bazel running - if no, let me know and we can try to get that done first. Once you have a version of Bazel that's compatible with TensorFlow running, I would try to run the TF build using `bazel build --jobs=1` to disable parallelism, as otherwise we'll run out of RAM. If this still gives you an error, could you post a longer log please?

**Comment by silver2row** [comment]
Hello,

Yes. I was trying to build it on the BBAI. Thank you but I think I have moved on for now. I might bring up another issue later.

Seth
