### ISSUE TITLE
Bazelisk subprocesses should prepend the correct bazel to the $PATH

### ISSUE THREAD

**Issue by gibfahn** [bazelbuild/bazelisk#111]
Many bazel rules end up running shell scripts that invoke `bazel`, which resolves to the first bazel binary in the path.

For example:

https://github.com/bazelbuild/rules_jvm_external/blob/0a7cc6a0b6764232a0ddd31ad87b489e1d47b166/private/pin.sh#L5

This should resolve to the `bazel` that `bazelisk` downloaded, otherwise you can end up using a different `bazel` binary in these subcommands. This causes confusing errors.

I believe the most natural fix would be for `bazelisk` to prepend a directory containing the relevant `bazel` binary to the `$PATH`.

**Comment by philwo** [comment]
I agree - this is a nice idea and would also improve the reliability of Bazel's CI, because some integration tests of downstream projects run `bazel` themselves and ended up using the wrong version in the past.

**Comment by coeuvre** [comment]
# Proposal

Prepend a directory containing relevant `bazel` binary to `PATH`.

## Changes

### Non-local Bazel binary

1. Currently, `bazelisk` download the required Bazel binary into `${os.UserCacheDir()}/bazelisk/bin/${bazelForkOrURL}` if user isn't using a local Bazel binary.

2. However, the name of downloaded binary is formated as `bazel-${version}-${osName}-${machineName}`. Typically, shell scripts use `bazel` directly, we can't simply prepend the directory of downloaded binary.

3. One solution would be that `bazelisk` download the Bazel binary into a directory which name is formated as `bazel-${version}-${osName}-${machineName}`. Inside that directory/subdirecotry, name the binary as `bazel`. For exampe:

   ```
   /Users/username/Library/Caches/bazelisk/downloads/bazelbuild
   |
   |---- bazel-3.3.1-darwin-x86_64
   |     |
   |     |---- bin
   |           |
   |           |---- bazel
   |
   |---- bazel-3.3.0-darwin-x86_64
   |     |
   |     |---- bin
   |           |
   |           |---- bazel
   ...
   ```

   

4. Then prepend `/Users/username/Library/Caches/bazelisk/downloads/bazelbuild/bazel-3.3.1-darwin-x86_64/bin` to `PATH`.

### Local Bazel binary

1. `bazelisk` will use user provided binary in their filesystem if `bazelVersionString` can be resolved to a local absolute file path.

2. However, we can't simply prepend the directory of that local binary to `PATH` as well since the name of that binary may not be `bazel`.

3. One solution is to create a directory under `${os.UserCacheDir()}/bazelisk/local` which name can be the absolute path of the user provided binary (replace invalid characters, of course). Inside that directory, create a symbolic link named `bazel` to the binary. For example, if `bazelVersionString="~/bazel-3.3.1"`:

   ```
   /Users/username/Library/Caches/bazelisk/local
   |
   |---- _Users_username_bazel-3.3.1
   |     |
   |     |---- bin
   |           |
   |           |---- bazel  --->  /Users/username/bazel-3.3.1
   ...
   ```

4. Prepend directory `/Users/username/Library/Caches/bazelisk/local/_Users_username_bazel-3.3.1/bin` to `PATH`.



# Concerns

1. The change for local Bazel binary case requires creating symbolic link which may not be supported well on `Windows`.
2. Existing users will need re-download Bazel binary for their required version.

**Comment by gibfahn** [comment]
>The change for local Bazel binary case requires creating symbolic link which may not be supported well on Windows.

Could we just fall back to copying the binary into the dir?

**Comment by keith** [comment]
Doesn't prepending this user specific directory to PATH break caching in some cases? I understand the use case for being able to correctly discover the `bazel` executable in scripts, but if you're not doing that doesn't this mean every action that respects PATH now includes the user name in it's action key on macOS?

**Comment by gibfahn** [comment]
In general (in my experience) if you want any kind of caching, especially when using a shared remote cache, you don't want to be passing env vars like `$PATH` to actions (i.e. you want to set `--incompatible_strict_action_env` etc.).

`PATH`s often have things in the homedir or user-specific things, e.g. right now my path has `~/bin` (my binaries/scripts), `~/Library/Python/3.9/bin` (python user packages), `~/code/path/to/python-project/.venv/bin` (virtualenv), `/Applications/kitty.app/Contents/MacOS` (Terminal Emulator). This seems no worse, as at least the dir is (I think) stable between Bazel executions as long as you don't upgrade your `.bazelversion`.

**Comment by keith** [comment]
Using `incompatible_strict_action_env` isn't ideal for macOS since it adds `/usr/local/bin` to the PATH which includes brew's default location and therefore pollutes many many binaries that aren't included in your setup. Setting PATH directly has been the only stable solution to this so far. For your other examples we explicitly want to exclude those things too, which is why we currently limit it to `/usr/bin:/bin`

**Comment by gibfahn** [comment]
>For your other examples we explicitly want to exclude those things too, which is why we currently limit it to /usr/bin:/bin

Yeah we do the same, with this in the `.bazelrc`:

```
--action_env=PATH=/bin:/usr/bin
```

I don't think Bazelisk prepedending itself to the PATH will matter in this case, it will just get ignored inside Bazel, and this feature just won't work right?

**Comment by keith** [comment]
Yea I think that will solve some more of these cases, I think we'd also have to do `--test_env=PATH=/usr/bin:/bin` in that case maybe. But Ideally we don't have to override PATH again for each possible option here which is why we're explicit about passing it when launching bazel instead

**Comment by keith** [comment]
We ended up adding a `tools/bazel` for bazelisk to pickup that re-sets the PATH correctly to avoid this issue.
