### ISSUE TITLE
create bazelisk github action

### ISSUE THREAD

**Issue by tmc** [bazelbuild/bazelisk#134]
An official bazelisk github action would be nice.

Prior art: https://github.com/cocotec/bazel-action

**Comment by mishas** [comment]
I've created a github action that is similar to other actions created by Github (similar to `setup-go`, `setup-node`, and others).

It also takes care of caching both bazelisk itself, and the bazel binary being used, and as such more efficient than the proposal above (and other bazelisk actions in the marketplace).

I give permission to bazelisk/bazelbuild to take ownership of the code, and copy it to bazelbuild/bazelisk-action.

https://github.com/marketplace/actions/setup-bazelisk

**Comment by philwo** [comment]
Thank you @mishas, that's very kind! I will check it out in the next days! 😊

**Comment by philwo** [comment]
Hi @mishas, just to follow up here, I need some more time to look into this - I want to play around with GitHub Actions a bit to get a good understanding of how it works and then I'll get back here. Thanks again for your contribution!

**Comment by thejasn** [comment]
Hey @philwo,
Any progress on this? Or can I go ahead with [setup-bazelisk](https://github.com/marketplace/actions/setup-bazelisk) that @mishas  setup?

**Comment by philwo** [comment]
Hey! Sorry for the delay and thank you for pinging me. Let's get this done, but I need your help a bit here to resolve some last questions. 😊

- @mishas, would you prefer to use the "Transfer repository" feature from GitHub to move your repository over to the bazelbuild organization? Or should we copy it so that your personal repository stays where it is?
- @mishas, just to make sure I fully understand - your repository is currently called `setup-bazelisk-action` and in your comment you said "[...] and copy it to `bazelbuild/bazelisk-action`" (without the `setup-` prefix). Is the name change intended?
- After transferring or copying the repo, how can we change https://github.com/marketplace/actions/setup-bazelisk to point to the new location in bazelbuild?

**Comment by mishas** [comment]
@philwo,

* I don't mind transferring the repository or just copying the files over. Up to you. Feels easier to create a completely new repo, and just copy the files, but (see point 3 regarding the marketplace listing), maybe if we transfer the repo, it'll make more sense.
* The naming `setup-bazelisk-action` was a mistake (as well as the `bazelbuild/bazelisk-action` comment). If we can call the new one `setup-bazelisk`, I think it'll be better, as it'll be in line with [setup-go](https://github.com/actions/setup-go) and other actions in https://github.com/actions. With that said, it's `actions/setup-*`, while here it'll be `bazelbuild/setup-bazelisk` - in which case, maybe a better name would be `bazelibuild/setup-aciton`? WDYT?
* That is a really great question! After we'll move the code, I can try the following:
    * I can delist my old action, and see if we can list the new one with that same name.
    * If we can't - I'll change documentation to be inline with the new action, and meanwhile contact Github support
    * In any case, I'll mark my current repository as deprecated, and point people to the official action.

**Comment by philwo** [comment]
Update from my side - Misha and me will figure out via VC how to transfer the repo and then report back here!

**Comment by philwo** [comment]
We have successfully moved the GitHub Action over to the bazelbuild organization:
- Repo: https://github.com/bazelbuild/setup-bazelisk
- Marketplace: https://github.com/marketplace/actions/setup-bazelisk

Thanks for your patience and thanks again Misha for the contribution.
