### ISSUE TITLE
Version in .bazelversion should be respected without WORKSPACE file

### ISSUE THREAD

**Issue by bmuschko** [bazelbuild/bazelisk#52]
## Issue

Executing the pre-built bazelisk binary doesn't seem to respect the value in a `.bazelversion` file when executed from the directory containing the file. The binary downloads the latest version of Bazel instead. Setting `USE_BAZEL_VERSION` picks up the correct version from the environment variable.

I believe the issue is that the determination of the `.bazelversion` file relies on the existence of a `WORKSPACE` file. For some of the "infrastructure" commands e.g. `version`, `help`, `info` this shouldn't be required.

## How to reproduce?

1. [Download bazelisk binary](https://github.com/philwo/bazelisk/releases/tag/v0.0.4) (in my case `bazelisk-darwin-amd64`)
2. Add the binary to PATH and add execution permission

```
cp bazelisk /Users/bmuschko/dev/tools/bazelisk
chmod +x /Users/bmuschko/dev/tools/bazelisk
export PATH=/Users/bmuschko/dev/tools:$PATH
```

3. Create a new directory and navigate to it

```
mkdir my-project
cd my-project
```

4. Add `.bazelversion` with version 0.21.0

```
echo 0.21.0 > .bazelversion
```

5. Run `bazelisk version`

```
Build label: 0.24.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Apr 2 16:32:47 2019 (1554222767)
Build timestamp: 1554222767
Build timestamp as int: 1554222767
```

**Comment by philwo** [comment]
I think we can change the logic to check for `.bazelversion` files from the current working directory up to the workspace root, but I'm not really sure what the use case is.

Except for `bazel help` or `bazel version` you can't do anything without a WORKSPACE file - not even `bazel info`:

```
$ bazel info
ERROR: The 'info' command is only supported from within a workspace (below a directory having a WORKSPACE file).
See documentation at https://docs.bazel.build/versions/master/build-ref.html#workspace
```

Could you explain a bit more why you'd need this?

**Comment by philwo** [comment]
@bmuschko Friendly ping - I'm curious about your use case for this. :)

**Comment by bmuschko** [comment]
@philwo When I opened the issue, I didn't realize that a WORKSPACE is pretty much required no matter what as I was very new to Bazel. IMHO it's not a use case. ;-)

**Comment by ian-h-chamberlain** [comment]
@philwo – I seem to have a use case for this. In my organization we use a strictly pinned version of `bazel` and so most of the organization has no need for a `.bazelversion` file. However, I would like to set for myself (e.g. in `~/.bazelversion`) a default version, while still creating specific workspaces with their own version (e.g. `~/my/workspace/.bazelversion`).

I can get around this with `USE_BAZEL_VERSION` but since it takes precedence over `.bazelversion` I don't have a great option to support multi-version for personal workspaces (with `.bazelversion`) vs shared workspaces (without `.bazelversion`).

From README.md:
> * Otherwise, if a .bazelversion file exists in the current directory or recursively any parent directory, it will read the file and use the version specified in it.

It would be nice if at least the documentation was updated to indicate the behavior, since there is no mention of the `WORKSPACE` file in the README.

**Comment by tirsen** [comment]
We're using bzlmod and instead of a WORKSPACE file we have a WORKSPACE.bzlmod file. It was really hard to understand why .bazelversion wasn't being used. Either .bazelversion should be used without a WORKSPACE file or WORKSPACE.bzlmod should also be or this should be clearly stated in the documentation. The current state of things is quite confusing.

**Comment by kjw-enf** [comment]
FIX: upgrade to latest bazelisk.

WORKAROUND: touch WORKSPACE (create a 0 byte file)

As users migrate to bzlmod, this error will crop up more often.

**Comment by keith** [comment]
https://github.com/bazelbuild/bazelisk/pull/805
