### ISSUE TITLE
Interaction with pyenv is breaking

### ISSUE THREAD

**Issue by natpen** [bazelbuild/bazelisk#6]
I'm not sure if this will be controversial as an issue, but I wanted to share a challenge I've faced trying to get Bazelisk working for my codebase. It has a lot to do with the lack of interpreter hermeticity in the Python rules, which is a separate problem, so this "issue" may also resolve itself in the future.

So, what happens is: if you manage your Python by way of [pyenv](https://github.com/pyenv/pyenv), the hashbang in this script (`#!/usr/bin/env python3`) will resolve to the pyenv shim for python 3. This will prepend things to PATH, and spawned subprocess will inherit the mutated PATH as _its_ environment. Further usage of python after bazelisk hands off control, then, end up getting forced onto python 3.

You could absolutely say this not Bazelisk's problem, but for what's it's worth, I worked around this by refactoring the script to be py2-compatible, and using `#!/usr/bin/python` as the hashbang - this should be portable across OSX and Linux, for the time being, and I'm hopeful the Bazel Python ecosystem will continue to improve so this is not something we have to worry about outside of the python rules themselves.

**Comment by philwo** [comment]
> You could absolutely say this not Bazelisk's problem, but for what's it's worth, I worked around this by refactoring the script to be py2-compatible, and using #!/usr/bin/python as the hashbang

This sounds like a good idea. I'd be happy to merge a PR that makes Bazelisk compatible with Python 2 and 3 at the same time. :)

**Comment by philwo** [comment]
Bazelisk (Python version) is now compatible with Python 2 and 3. I'm adding a test that ensures that this continues to be the case.

For the hashbang line, I'm not sure what to do. It seems like there's just no good way to ensure that it works on all systems: https://blogs.gnome.org/mcatanzaro/2018/02/16/on-python-shebangs/

I'd say - feel free to replace it with whatever fits your use case best.

I'll leave it like this for now, also because Bazel's way of finding Python installations on the system [has changed a lot in the last release](https://github.com/bazelbuild/bazel/issues/7899) and the Go version of Bazelisk is gaining more traction and features. Hope that's OK with you!
