### ISSUE TITLE
If //tools/bazel points to bazelisk, infinite fork happens

### ISSUE THREAD

**Issue by kellycampbell** [bazelbuild/bazelisk#61]
We have been using //tools/bazel to execute bazelisk and then that picks up which version to run via .bazelversion.

Change #53 broke this. 

Would it be possible to add a cmd line flag to disable this feature?

**Comment by philwo** [comment]
Sorry for that, @kellycampbell! I'll see that we fix this quickly.

Can you describe your setup in more detail, so that I can reproduce this on my machine?
- What is //tools/bazel exactly - a shell script that somehow executes Bazelisk (if yes, how) or Bazelisk itself?
- Are you using the Python version of Bazelisk or the Go version?

**Comment by kellycampbell** [comment]
I believe we're using the Go version.

Here's our //tools/bazel:

```
#!/bin/bash

set -eu

BAZELISK_VERSION=0.0.4
BAZELISK_DIR="$(dirname "${BASH_SOURCE[0]}")/bazelisk"

if [ "$(uname -s)" == "Darwin" ]; then
    BAZELISK="${BAZELISK_DIR}/bazelisk-${BAZELISK_VERSION}-darwin-amd64"
elif [ "$(uname -s)" == "Linux" ]; then
    BAZELISK="${BAZELISK_DIR}/bazelisk-${BAZELISK_VERSION}-linux-x86_64"
fi

exec -a "$0" "${BAZELISK}" "$@"
```

**Comment by philwo** [comment]
Thanks! I'll look into this and will get back to you tomorrow :)
