### ISSUE TITLE
support external servers for internal builds

### ISSUE THREAD

**Issue by nevion** [bazelbuild/bazelisk#72]
bazelisk is a really nice concept - would be more useful to me by having easily able to use a particular host for bazel builds, which may not be upstream's builds (or hashes).

What might build a bridge to supporting that well?  Listing providers in the .bazelversion?  What about on the server side?

**Comment by FaBrand** [comment]
We have a similar Situation at work.
We use bazel with bazelisk quite extensively and i was thrilled to read the enterprise ready 1.0 Release.
However this assumes that the fork resides on github.com and does not allow for different URLs from local Systems
e.g. `github.company.com/api/...`

I already had some thoughts about how to provide this Information.

First idea i came up with was to extend the pattern that is already used with the fork Version.
However this has the drawback that each User needs to write out the whole shebang everytime, when testing with a different Version.
That lead me to my second thought

Having e.g. a `.bazeliskrc` could store that information better and statically per repo.
So the User could still use just `USE_BAZEL_VERSION=0.XX.X`
And bazelisk takes the repo/api URL from the rc file.

I would be glad to know what you think about that. If you agree, i could open a PR, but would need some help through review since my GO proficiency is not that well (yet) :grin:

**Comment by philwo** [comment]
We actually need a similar feature inside Google, too. I'd be happy to review a PR and no worries about the Go proficiency, I'm also figuring this out as we go here. ;)

Let me think a bit about a possible design and get back to this on Friday!

@nevion, @FaBrand and others, feel free to discuss your requirements here, so that we can make sure to address everyone's use case. For example, being able to get the binaries from a local directory instead of an HTTP server might useful for us.

**Comment by nevion** [comment]
@FaBrand  - do you mean the use indicates a version (perhaps with additional version tags) and the bazeliskrc maps that version (could be a simple normal version revision, but user wants a forked bazel) into a provider/repository/path?

I could make either user tagged versions or plain bazel versions work, but it is probably better to be able to override something like 1.0.0 to be your own package implementation.  In my case I've got trivial patches that make bazel recognize cuda as c++ through file extension handling, and maybe some ld script extensions still.

@philwo Yes, I think to cover my use cases being able to try both disk and http, a sort of availability mirroring is highly desirable over just having an http url to support a variety of common user cases (intranet, remote, no internet), disk only paths have other reasons for wanting (security) too.  It would also be nice if the complexity of the file (the one hiding behind github.com/.../api/) was not very complicated and human maintainable.  Speaking of no internet, just to make sure, if all assets required to build were downloaded previously, making sure that if internet goes away, that things work is definitely good to have.

- [ ] support http and disk paths
- [ ] support no internet access after assets have been downloaded
- [ ] map simple / plain bazel versions into custom bazel builds (as well as user tagged versions)

**Comment by cgruber** [comment]
Thinking about this for our own needs, I"m not sure if it makes sense to just support a version, a URL, or a separately configured version and url template.  The quick and dirty is to just support a URL in place of a version string. But... in our case, a url can't work simplicitur because the url carries both version and platform information. (e.g. darwin vs. linux).

**Comment by FaBrand** [comment]
@nevion @philwo I finally found the time to prepare a draft. What do you think about #91 ?

**Comment by gibfahn** [comment]
Was this fixed by https://github.com/bazelbuild/bazelisk/pull/107?

**Comment by philwo** [comment]
In a way.. yes! Thanks. :)

#107 added support for fetching Bazel from custom URLs and @fweikert's recent refactoring added support for implementing custom repositories by implementing the ReleaseRepo / CandidateRepo / ForkRepo / ... interfaces. For example, inside Google we have a custom repository class that fetches the binaries and version info from a network filesystem. With a simple custom main method you can then wire it up so that Bazelisk uses this repository for everything.

I'll close this, if there's anything missing please feel free to open a new more specific issue or comment here!
