### ISSUE TITLE
Flakyness when using Bazelisk on GCB builds

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/bazelisk#74]
We recently switched to using Bazelisk in many tests that run on bazel-toolchains repo using GCB triggers. Today we're seeing some of our builds fail with the following error:
`Step #0: 2019/06/28 17:42:34 could not download Bazel: could not copy from https://releases.bazel.build/0.27.0/release/bazel-0.27.0-linux-x86_64 to /root/.cache/bazelisk/bin/download895442339: stream error: stream ID 1; INTERNAL_ERROR`
Seems to be flakiness, as retrying the test usually succeeds

**Comment by philwo** [comment]
I'm dreaming of the day when Google Cloud Storage will be as reliable as a simple nginx webserver...

Are you still seing this, or did it stop after a while? If you're still seeing this, it might point to some issue in the infrastructure between GCB and GCS, otherwise it was just normal GCS flakyness.

**Comment by nlopezgi** [comment]
I'm not seeing it often, but it does come up in, lets say, 1 out of 100
builds (we just have a lot of GCB builds now). So yes, lets just call it
normal GCS flakyness for now. I'll let you know if we see it more often or
it becomes a problem.

**Comment by philwo** [comment]
We could add a retry logic for the download in case it unexpectedly aborts.

**Comment by nlopezgi** [comment]
We have not really seen this happen again in a while. I'll let you know if it becomes a problem again. Closing.
