### ISSUE TITLE
undefined: os.UserCacheDir

### ISSUE THREAD

**Issue by borkaehw** [bazelbuild/bazelisk#78]
I am trying to install Go version as it describes in `README.md`, but I got a message when I ran
```
go get github.com/bazelbuild/bazelisk
```
The message is
```
# github.com/bazelbuild/bazelisk
go/src/github.com/bazelbuild/bazelisk/bazelisk.go:606:24: undefined: os.UserCacheDir
```
I am running
```
Ubuntu 18.04.1 LTS
go version go1.10.4 linux/amd64
```
Could anyone take a look what I did wrong? Thanks.

**Comment by borkaehw** [comment]
It seems like this version works for me
```
go version go1.12.6 linux/amd64
```

**Comment by philwo** [comment]
@borkaehw Just to follow up here: The function `os.UserCacheDir` was added in Go 1.11, so the version that Ubuntu 18.04 ships is too old.

I'll add it to the README.

**Comment by stweil** [comment]
The README starts with _A user-friendly launcher for Bazel._

I read it because I need Bazel for building TensorFlow. And of course I did not notice the remark about Go 1.11, but got the error. Only after searching for the error message, I found the information given here.

_User friendly_ would catch the wrong version of go and directly report the requirement. Even better, it would implement a different solution for Go 1.10 (still standard in LTS version of Ubuntu). I don't mind which cache directory is used.

Please don't get me wrong. I estimate your work, but think it might be useful for you to get feedback from users like me.

**Comment by philwo** [comment]
@stweil Thank you for your feedback! I'm curious why you tried to build Bazelisk from source instead of using one of the pre-built binaries that I provide for each release. I mean, building from source is always nice, but I was wondering if there's a particular other reason, e.g. I'm not providing binaries for your platform, or the release binaries are not easy to find on GitHub and should be pointed out in the README much more visibly or some other reason. :)

I'll also try to make the build from source process easier.

**Comment by stweil** [comment]
As far as I know there are no Bazelisk binaries for Ubuntu on Power8 or ARM, the hosts for which I need TensorFlow which requires Bazel.

**Comment by philwo** [comment]
>  there are no Bazelisk binaries for Ubuntu on Power8 or ARM

@stweil Bazelisk's purpose is to automatically download the correct official Bazel release binary for your platform and project.

Bazel is not officially supported on Power8 or ARM. You might find community-provided binaries out there or be able to build Bazel on these platforms yourself, but the Bazel project itself neither tests on these platforms, nor provides official release binaries. This might change in the future (I'm personally working on it as time permits), but that's the current situation. Thus, even if Bazelisk ran on these platforms - what would it do? There are no Bazel binaries it could download.

Because of that, I didn't provide Bazelisk binaries for these platforms yet. It would technically be no problem - it's a two line change to the `build.sh` file, but I didn't see the point. Users would just be frustrated when downloading the binary and finding out that it can't do anything for them. :(

I will take a note that Power8 and ARM binaries would be useful for you. I hope I can provide these (and Bazelisk binaries) in the near future.
